/* Script de la db */

USE db;

INSERT INTO personaje(nombre, imagen, descripcion)
VALUES
('Iron Man', 'iron_man.jpg', 
'Más conocido como Tony Stark, es un multimillonario magnate empresarial, filántropo, playboy e ingenioso científico'),
('Thor', 'thor.jpg', 'Dios del trueno y fuerza en la mitología nórdica y germánica'),
('Valkiria', 'valkiria.jpg', 
'Conocida por su destreza en la batalla, a menudo se acompaña de su caballo alado Aragorn y lleva la espada encantada Dragonfang'),
('Capitán América', 'capitan_america.jpg',
'Cuyo nombre real es Steven Grant Rogers, es un super soldado de los Estados Unidos de América'),
('Capitana Marvel', 'capitana_marvel.jpg', 
'Cuyo nombre real es Carol Danvers, después de que su ADN se fusionara con el de Mar-Vell, obtiene poderes sobrehumanos'),
('Black Widow','black_widow.jpg',
'Experta espía y combatiente cuerpo a cuerpo. Convocada por Nick Fury, es miembro fundador de la Iniciativa Vengadores.'),
('Hawkeye', 'hawkeye.jpg',
'Su nombre real es Clint Barton. Tirador experto y un combatiente cuerpo a cuerpo, siendo su arma preferida es un arco recurvo.'),
('Hulk', 'hulk.jpg',
'Ser humanoide enorme de piel verde, corpulento y musculoso que posee una gran fortaleza física.'),
('Kate Bishop', 'kate_bishop.jpg',
 'Miembro de los Jóvenes Vengadores. Tomar el nombre del Ojo de Halcón (Hawkeye) después de Clint Barton'),
('Lady Thor', 'lady_thor.jpg',
'Cuyo nombre es Jane Foster, científica astrofísica. Al hacerse con la legendaria arma llamada Mjölnir, obtiene los poderes de Thor'),
('Star Lord', 'star_lord.jpg', 
'Híbrido Celestial-humano, legendario forajido, líder de Los Guardianes de la Galaxia.'),
('Ultron', 'ultron.jpg', 'Inteligencia artificial que trata de eliminar a los superheroes.'),
('Venom', 'venom.jpg', 
'Simbionte con una forma amorfa, semi-líquido, que sobrevive mediante la unión con un huésped, por lo general humano.'),
('Black Panther', 'black_panther.jpg',
'Rey y protector de Wakanda, poseer habilidades mejoradas logradas a través de rituales antiguos de Wakanda.'),
('Doctor Strange', 'doctor_strange.jpg', 
'Poderoso hechicero y miembro destacado de los Maestros de las Artes Místicas.'),
('Loki','loki.jpg',
'Dios de las Mentiras, Prínciper de Asgard, hermano de Thor'),
('Scarlet Witch', 'scarlet_witch.jpg',
'Posee habilidades para alterar la realidad de formas no especificadas y es, además, una poderosa hechicera.'),
('Shang-Chi', 'shang-chi.jpg',
'Maestro de artes marciales con habilidades insuperables por muchos, heredero de los Anillos Místicos.'),
('Deadpool', 'deadpool.jpg', 
'Mercenario y antiheroe, mentalmente inestable y desfigurado'),
('Duende Verde', 'duende_verde.jpg', 
'Supervillano con temática de Halloween cuyas armas se asemejan a murciélagos, fantasmas y linternas de calabaza. Es estrambótico, bocazas y políticamente incorrecto.');
